disabled_rules:
  - identifier_name

line_length:
  warning: 200
  error: 300

cyclomatic_complexity:
  warning: 20
  error: 35

file_length:
  warning: 1400
  error: 1500

function_body_length:
  warning: 75
  error: 100

type_body_length:
  warning: 400
  error: 600

large_tuple:
  warning: 4
  error: 6
